### ISSUE TITLE
Merkle root = correlatable identifier?

### ISSUE THREAD

**Issue by peacekeeper** [transmute-industries/merkle-disclosure-proof-2021#5]
If I understand correctly, the merkle root is always included in a derived proof and revealed to a Verifier. This means that there is always a globally correlatable identifier for the subject. Not saying that this makes the suite less cool, but it should probaby be mentioned in a Privacy Considerations sections, especially since this specification compares itself to CL and BBS+ Signatures.

**Comment by OR13** [comment]
Good point, I should also comment on the required field `issuanceDate` in that case as well.

**Comment by OR13** [comment]
I added a section in https://github.com/transmute-industries/merkle-disclosure-proof-2021/pull/7

**Comment by peacekeeper** [comment]
Looks good, closing.
